### ISSUE TITLE
Replace with getDerivedStateFromProps

### ISSUE THREAD

**Issue by kate-ivanova** [AleksandrLv/react-css-animated#1]
We need to replace this deprecated method with [getDerivedStateFromProps](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops)
https://github.com/AleksandrLv/react-css-animated/blob/323ffab48176eaab2c527908dff278c0105366b6/src/index.js#L16

**Comment by AleksandrLv** [comment]
> We need to replace this deprecated method with [getDerivedStateFromProps](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops)
> https://github.com/AleksandrLv/react-css-animated/blob/323ffab48176eaab2c527908dff278c0105366b6/src/index.js#L16

@kate-ivanova Done! :)
